### ISSUE TITLE
Router redirect component is incorrect (either docs or component)

### ISSUE THREAD

**Issue by DavidFrahm** [ionic-team/stencil-site#258]
In the [redirect docs](https://stenciljs.com/docs/router-tutorials#create-a-redirect) the component listed as `<stencil-route-redirect>` is incorrect. The correct component name is `<stencil-router-redirect>`. (Notice the "r" on the end of "router").

I was about to submit a fix for that, but given that all the other stencil components use "route", and Ionic redirect uses "route" (`<ion-route-redirect>`), maybe the component should be changed to match the docs as `<stencil-route-redirect>`?

That makes more sense to me, and seems the naming that would result in fewer people getting tripped up like I just did.

**Comment by rwaskiewicz** [comment]
Thanks! I apologize that no one from the Stencil team at the time responded to this issue. I appreciate the effort in helping make our docs better. Since this issue was originally created, we have since moved the Stencil router to the Stencil Community model, and are no longer supporting it in an effort to focus more on component library development. I'm going to close this issue, but thanks again for using Stencil!
