### ISSUE TITLE
Add docs for querying Local DOM

### ISSUE THREAD

**Issue by splitinfinities** [ionic-team/stencil-site#34]
Polymer provides `this.$.item` in order to access parts of the template. Documenting how to use this would be beneficial to newcomers.

**Comment by splitinfinities** [comment]
Closing, already exists: https://stenciljs.com/docs/decorators#element-decorator

**Comment by kylecordes** [comment]
@splitinfinities That doc page shows how to easily get access to the elements "root" DOM element. How about adding a bit to doc or a line to the code snippet, which points developers to `todoListEl.querySelector('.blah')....` to get access to a different piece of the component DOM?

(I'm guessing that the recommendation is "just use the platform" in this way - that is what I see it in use in the Ionic Stencil branches. Rather than, say, something like what Angular, Vue, and other frameworks provide as a different means to refer to an element within a component.)

**Comment by splitinfinities** [comment]
@kylecordes I'm going to open an issue about docs hierarchy, because in it's current state, there are things that are easy to miss. I think in this case, a page for each decorator stencil provides will help, as well as a landing/archive page that details a high-level of the components available. 

`@Element` does solve my initial problem, but I simply missed it in the docs. So giving `@Element` it's own page can help provide that example, without taking space from other decorators.
