### ISSUE TITLE
On Android (Pixel XL - any Chrome browser) there is black flicker when changing route

### ISSUE THREAD

**Issue by kenchris** [ionic-team/stencil-site#44]
On Android (Pixel XL - any Chrome browser) there is black flicker when changing route

Tested in Canary, Beta, Dev and Stable

**Comment by jgw96** [comment]
This black flicker was caused by the content re-rendering while scrolling up. This was fixed by https://github.com/ionic-team/stencil-site/commit/d1f687b1f3ed6b3658ea9dd1bc012d972941a479. There is however another flicker issue when going between, for example, the root page and resources page. This is a bug in our router that is being fixed.
