### ISSUE TITLE
Improving getting started documentation

### ISSUE THREAD

**Issue by henrydaggett** [ionic-team/stencil-site#817]
The "Getting Started" and "My First Component" docs are great, but I think one thing that's missing is how to go from `npm stencil init` to starting a dev server.

It could be great to detail in one or other of the sections that after `init` you need to run `npm install` and after that run one of the server commands like `npm start`.

I think this fills in the knowledge gap in the getting started process.

**Comment by rwaskiewicz** [comment]
Hey @henrydaggett - with #829 being merged, this issue was auto-closed by GitHub. I've updated the documentation, which I believe addresses your concerns. You can view the changes live at https://stenciljs.com/docs/getting-started (you may need to hard refresh to bust the cache). If you have any additional thoughts/comments/concerns, feel free to open a new issue (or PR if you'd like to use #829 as a starting ground!). Thanks again!
